services:

  ubuntu_24.04:
    image: hudsonventura/headless:ubuntu_24.04
    build:
      context: ./
      dockerfile: Dockerfile_ubuntu_24.04
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - VNC_PW=password
      - SCREEN_RESOLUTION=1280x720
    restart: unless-stopped

  almalinux_9:
    image: hudsonventura/headless:almalinux_9
    build:
      context: ./
      dockerfile: Dockerfile_almalinux_9
    ports:
      - "5902:5901"
      - "6902:6901"
    environment:
      - VNC_PW=password
      - SCREEN_RESOLUTION=1280x720
    restart: unless-stopped

